os: osx
osx_image: xcode12.5
language: swift
branches:
  only:
  - master
script: xcodebuild clean build test -project PodcastKo/PodcastsKo.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
