os: osx
osx_image: xcode12.5
language: swift
script: xcodebuild clean build test -project PodcastKo/PodcastsKo.xcodeproj -scheme "CI_macOS" -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES